# nixpacks.toml
# https://nixpacks.com/docs/configuration/file

[variables]
# Set the node version
NODE_VERSION = "18"
# Set Caddy version to match Railway's examples
CADDY_VERSION = "2.7.6"

[phases.setup]
# Install Caddy - following Railway's exact pattern
cmds = [
    "curl -fsSLo caddy.tar.gz \"https://github.com/caddyserver/caddy/releases/download/v${CADDY_VERSION}/caddy_${CADDY_VERSION}_linux_amd64.tar.gz\"",
    "tar -xzf caddy.tar.gz caddy",
    "chmod +x caddy",
    "ls -la caddy"
]

[phases.install]
# Install dependencies
cmds = ["npm ci --production=false"]

[phases.build]
# Build the React app
cmds = ["npm run build"]

[start]
# Use Caddy to serve the built React app with explicit path
cmd = "/app/caddy run --config /app/Caddyfile --adapter caddyfile 2>&1" 