[phases.setup]
nixPkgs = ['nodejs_22', 'npm-9_x']

[phases.install]
dependsOn = ['setup']
cmds = ['cd backend && npm install --production=false']

[start]
cmd = 'cd backend && npm start'

[variables]
NODE_ENV = 'production' 