[phases.setup]
nixPkgs = ['nodejs_22', 'npm-9_x']

[phases.install]
cmds = ['npm install --production=false']

[phases.build]
cmds = ['echo "Backend ready - no build step needed"']

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production' 